"""
Manual test script: render one Manim episode from a hardcoded JSON
payload and (optionally) upload the result to Firebase.

This is NOT part of the FastAPI app -- run it directly:
    python scripts/test_manim_render.py

It exists so you can verify Manim output looks right before wiring
the orchestrator -> manim_engine -> video_storage chain together.
"""

import sys
import os

# allow `from app.services... import ...` when running this script directly
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.services.manim_engine import Manim_Engine

# Replace with a real Production Plan episode once your orchestrator exists.
# For now, hand-write one to confirm Manim itself renders correctly.
sample_episode = {
      "episode_number": 3,
      "title": "การเคลื่อนที่แบบโพรเจกไทล์: ปาก้อนหินมุมก้ม",
      "core_vocabulary": ["โพรเจกไทล์", "ความเร็วต้น", "มุมก้ม", "แนวดิ่ง", "แนวราบ", "ความเร่งโน้มถ่วง", "สมการกำลังสอง"],
      "video_plan": {
        "estimated_duration_seconds": 96,
        "visual_cues": "แสดงกราฟการเคลื่อนที่แบบโพรเจกไทล์จากที่สูงด้วยมุมก้ม พร้อมจุดเริ่มต้น จุดตก เวกเตอร์ความเร็วต้น และมุม จากนั้นแสดงสมการคำนวณการแตกแรง เวลา และระยะทางในโซนล่าง",
        "audio_cues": "อธิบายโจทย์, อธิบายภาพการเคลื่อนที่, อธิบายขั้นตอนการคำนวณการแตกแรง เวลา และระยะทาง"
      },
      "script": {
        "hook": "มาถึงโจทย์สุดท้ายกันครับ ชายคนหนึ่งยืนอยู่บนดาดฟ้าตึกสูง 50 เมตร แล้วปาก้อนหินออกไปในแนวทำมุมก้ม 37 องศากับแนวระดับ ด้วยความเร็ว 25 เมตรต่อวินาที เราต้องหาว่านานเท่าใดก้อนหินจึงจะตกถึงพื้น และตกห่างจากตัวตึกเท่าใด",
        "main_body": "ในกรณีนี้ ก้อนหินถูกปาลงมาเป็นมุมก้ม 37 องศา ทำให้มันมีความเร็วต้นทั้งในแนวราบและแนวดิ่ง โดยความเร็วในแนวดิ่งจะชี้ลงตั้งแต่แรก ทำให้ก้อนหินตกลงสู่พื้นเร็วกว่าการปาในแนวระดับ ลองดูวิถีโค้งที่เกิดขึ้นบนจอได้เลยครับ\nขั้นตอนแรก เราต้องแตกความเร็วต้น 25 เมตรต่อวินาที ออกเป็นองค์ประกอบในแนวราบและแนวดิ่งก่อนครับ ความเร็วในแนวราบ วีเอ็กซ์ เท่ากับ 25 คูณ โคไซน์ 37 องศา ได้ประมาณ 19.97 เมตรต่อวินาที ส่วนความเร็วต้นในแนวดิ่ง ยูวาย เท่ากับ ลบ 25 คูณ ไซน์ 37 องศา ได้ประมาณ ลบ 15.05 เมตรต่อวินาที เครื่องหมายลบแสดงว่าทิศทางชี้ลงครับ\nขั้นตอนที่สอง เราจะหาเวลาที่ก้อนหินตกถึงพื้น โดยใช้สมการการเคลื่อนที่ในแนวดิ่ง จากสมการ เอสวาย เท่ากับ ยูวาย ที บวก หนึ่งส่วนสอง จีที กำลังสอง แทนค่าความสูง 50 เมตร ความเร็วต้นแนวดิ่ง ลบ 15.05 และค่าจีเป็น 10 จัดรูปสมการจะได้ 5 ที กำลังสอง บวก 15.05 ที ลบ 50 เท่ากับศูนย์ ใช้สูตรหาคำตอบของสมการกำลังสอง แทนค่าลงไป\nขั้นตอนสุดท้าย เราจะหาระยะทางที่ก้อนหินตกห่างจากตัวตึกในแนวราบ จากสมการ เอสเอ็กซ์ เท่ากับ วีเอ็กซ์ คูณ ที แทนค่า วีเอ็กซ์ 19.97 เมตรต่อวินาที และเวลา 2.00 วินาที",
        "example_or_trick": "คำนวณออกมาจะได้เวลาประมาณ 2.00 วินาที ดังนั้น ก้อนหินจะตกห่างจากตัวตึกประมาณ 39.94 เมตรครับ",
        "call_to_action": "โจทย์นี้แสดงให้เห็นว่าการปาวัตถุในมุมก้มทำให้วัตถุตกถึงพื้นเร็วขึ้นและมีวิถีโค้งที่แตกต่างออกไป หวังว่าทุกคนจะเห็นภาพการเคลื่อนที่แบบโพรเจกไทล์ชัดเจนขึ้นนะครับ ถ้าชอบเนื้อหาแบบนี้ อย่าลืมกดติดตาม pageSpark นะครับ"
      },
      "voiceover_script": [
        {
          "segment_id": "hook_problem_1",
          "phase": "hook_problem",
          "thai_text": "มาถึงโจทย์สุดท้ายกันครับ ชายคนหนึ่งยืนอยู่บนดาดฟ้าตึกสูง 50 เมตร แล้วปาก้อนหินออกไปในแนวทำมุมก้ม 37 องศากับแนวระดับ ด้วยความเร็ว 25 เมตรต่อวินาที เราต้องหาว่านานเท่าใดก้อนหินจึงจะตกถึงพื้น และตกห่างจากตัวตึกเท่าใด",
          "start_time_seconds": 0.0,
          "end_time_seconds": 11.75,
          "start_frame": 0,
          "end_frame": 705,
          "synced_visual_action": "Write(title_text) และ FadeIn(problem_statement)"
        },
        {
          "segment_id": "diagram_explain_2",
          "phase": "diagram_explain",
          "thai_text": "ในกรณีนี้ ก้อนหินถูกปาลงมาเป็นมุมก้ม 37 องศา ทำให้มันมีความเร็วต้นทั้งในแนวราบและแนวดิ่ง โดยความเร็วในแนวดิ่งจะชี้ลงตั้งแต่แรก ทำให้ก้อนหินตกลงสู่พื้นเร็วกว่าการปาในแนวระดับ ลองดูวิถีโค้งที่เกิดขึ้นบนจอได้เลยครับ",
          "start_time_seconds": 12.25,
          "end_time_seconds": 22.83,
          "start_frame": 735,
          "end_frame": 1370,
          "synced_visual_action": "Create(axes_group) พร้อมแสดงวิถีโค้ง, จุดเริ่มต้น, จุดตก, เวกเตอร์ความเร็วต้น และเส้นประบอกระยะ"
        },
        {
          "segment_id": "step_solve_3",
          "phase": "step_solve",
          "thai_text": "ขั้นตอนแรก เราต้องแตกความเร็วต้น 25 เมตรต่อวินาที ออกเป็นองค์ประกอบในแนวราบและแนวดิ่งก่อนครับ",
          "start_time_seconds": 23.63,
          "end_time_seconds": 28.96,
          "start_frame": 1417,
          "end_frame": 1737,
          "synced_visual_action": "FadeOut(problem_statement, shift=DOWN*0.1), FadeIn(step1_group[0]), Write(step1_group[1])"
        },
        {
          "segment_id": "step_solve_4",
          "phase": "step_solve",
          "thai_text": "ความเร็วในแนวราบ วีเอ็กซ์ เท่ากับ 25 คูณ โคไซน์ 37 องศา ได้ประมาณ 19.97 เมตรต่อวินาที",
          "start_time_seconds": 29.76,
          "end_time_seconds": 35.83,
          "start_frame": 1785,
          "end_frame": 2150,
          "synced_visual_action": "Write(eq1_2)"
        },
        {
          "segment_id": "step_solve_5",
          "phase": "step_solve",
          "thai_text": "ส่วนความเร็วต้นในแนวดิ่ง ยูวาย เท่ากับ ลบ 25 คูณ ไซน์ 37 องศา ได้ประมาณ ลบ 15.05 เมตรต่อวินาที เครื่องหมายลบแสดงว่าทิศทางชี้ลงครับ",
          "start_time_seconds": 36.63,
          "end_time_seconds": 46.05,
          "start_frame": 2197,
          "end_frame": 2763,
          "synced_visual_action": "Write(eq1_3), Write(eq1_4)"
        },
        {
          "segment_id": "step_solve_6",
          "phase": "step_solve",
          "thai_text": "ขั้นตอนที่สอง เราจะหาเวลาที่ก้อนหินตกถึงพื้น โดยใช้สมการการเคลื่อนที่ในแนวดิ่ง",
          "start_time_seconds": 46.85,
          "end_time_seconds": 52.0,
          "start_frame": 2811,
          "end_frame": 3120,
          "synced_visual_action": "Transform(step1_group, step2_group)"
        },
        {
          "segment_id": "step_solve_7",
          "phase": "step_solve",
          "thai_text": "จากสมการ เอสวาย เท่ากับ ยูวาย ที บวก หนึ่งส่วนสอง จีที กำลังสอง",
          "start_time_seconds": 52.8,
          "end_time_seconds": 57.72,
          "start_frame": 3168,
          "end_frame": 3463,
          "synced_visual_action": "Write(eq2_1)"
        },
        {
          "segment_id": "step_solve_8",
          "phase": "step_solve",
          "thai_text": "แทนค่าความสูง 50 เมตร ความเร็วต้นแนวดิ่ง ลบ 15.05 และค่าจีเป็น 10",
          "start_time_seconds": 58.52,
          "end_time_seconds": 63.77,
          "start_frame": 3511,
          "end_frame": 3826,
          "synced_visual_action": "Write(eq2_2)"
        },
        {
          "segment_id": "step_solve_9",
          "phase": "step_solve",
          "thai_text": "จัดรูปสมการจะได้ 5 ที กำลังสอง บวก 15.05 ที ลบ 50 เท่ากับศูนย์",
          "start_time_seconds": 64.57,
          "end_time_seconds": 69.82,
          "start_frame": 3874,
          "end_frame": 4189,
          "synced_visual_action": "Write(eq2_3)"
        },
        {
          "segment_id": "step_solve_10",
          "phase": "step_solve",
          "thai_text": "ใช้สูตรหาคำตอบของสมการกำลังสอง",
          "start_time_seconds": 70.62,
          "end_time_seconds": 73.62,
          "start_frame": 4237,
          "end_frame": 4417,
          "synced_visual_action": "Write(eq2_4)"
        },
        {
          "segment_id": "step_solve_11",
          "phase": "step_solve",
          "thai_text": "แทนค่าลงไป",
          "start_time_seconds": 74.42,
          "end_time_seconds": 76.25,
          "start_frame": 4465,
          "end_frame": 4575,
          "synced_visual_action": "Write(eq2_5)"
        },
        {
          "segment_id": "step_solve_12",
          "phase": "step_solve",
          "thai_text": "คำนวณออกมาจะได้เวลาประมาณ 2.00 วินาที",
          "start_time_seconds": 77.05,
          "end_time_seconds": 80.69,
          "start_frame": 4623,
          "end_frame": 4841,
          "synced_visual_action": "Write(eq2_6)"
        },
        {
          "segment_id": "step_solve_13",
          "phase": "step_solve",
          "thai_text": "ขั้นตอนสุดท้าย เราจะหาระยะทางที่ก้อนหินตกห่างจากตัวตึกในแนวราบ",
          "start_time_seconds": 81.49,
          "end_time_seconds": 86.82,
          "start_frame": 4889,
          "end_frame": 5209,
          "synced_visual_action": "Transform(step2_group, step3_group)"
        },
        {
          "segment_id": "step_solve_14",
          "phase": "step_solve",
          "thai_text": "จากสมการ เอสเอ็กซ์ เท่ากับ วีเอ็กซ์ คูณ ที",
          "start_time_seconds": 87.62,
          "end_time_seconds": 90.62,
          "start_frame": 5257,
          "end_frame": 5437,
          "synced_visual_action": "Write(eq3_1)"
        },
        {
          "segment_id": "step_solve_15",
          "phase": "step_solve",
          "thai_text": "แทนค่า วีเอ็กซ์ 19.97 เมตรต่อวินาที และเวลา 2.00 วินาที",
          "start_time_seconds": 91.42,
          "end_time_seconds": 95.34,
          "start_frame": 5485,
          "end_frame": 5720,
          "synced_visual_action": "Write(eq3_2)"
        },
        {
          "segment_id": "step_solve_16",
          "phase": "step_solve",
          "thai_text": "ดังนั้น ก้อนหินจะตกห่างจากตัวตึกประมาณ 39.94 เมตรครับ",
          "start_time_seconds": 96.14,
          "end_time_seconds": 99.97,
          "start_frame": 5768,
          "end_frame": 5998,
          "synced_visual_action": "Write(eq3_3)"
        },
        {
          "segment_id": "cta_17",
          "phase": "cta",
          "thai_text": "โจทย์นี้แสดงให้เห็นว่าการปาวัตถุในมุมก้มทำให้วัตถุตกถึงพื้นเร็วขึ้นและมีวิถีโค้งที่แตกต่างออกไป หวังว่าทุกคนจะเห็นภาพการเคลื่อนที่แบบโพรเจกไทล์ชัดเจนขึ้นนะครับ ถ้าชอบเนื้อหาแบบนี้ อย่าลืมกดติดตาม pageSpark นะครับ",
          "start_time_seconds": 100.77,
          "end_time_seconds": 110.11,
          "start_frame": 6046,
          "end_frame": 6606,
          "synced_visual_action": "FadeOut(step3_group, shift=DOWN*0.1), FadeOut(title_text, shift=UP*0.1)"
        }
      ],
      "manim_code_lines": [
        "import numpy as np",
        "from manim import *",
        "",
        "config.pixel_width = 1080",
        "config.pixel_height = 1920",
        "config.frame_height = 16.0",
        "config.frame_width = 9.0",
        "config.frame_rate = 60",
        "",
        "class PhysicsScene(Scene):",
        "    def construct(self):",
        "        self.camera.background_color = '#1C1C2E'",
        "        frame_height = config.frame_height",
        "        frame_width = config.frame_width",
        "        top_zone_height = frame_height * 0.20",
        "        middle_zone_height = frame_height * 0.45",
        "        bottom_zone_height = frame_height * 0.35",
        "        top_zone_top = frame_height / 2",
        "        top_zone_bottom = top_zone_top - top_zone_height",
        "        top_zone_center_y = (top_zone_top + top_zone_bottom) / 2",
        "        middle_zone_top = top_zone_bottom",
        "        middle_zone_bottom = middle_zone_top - middle_zone_height",
        "        middle_zone_center_y = (middle_zone_top + middle_zone_bottom) / 2",
        "        bottom_zone_top = middle_zone_bottom",
        "        bottom_zone_bottom = bottom_zone_top - bottom_zone_height",
        "        bottom_zone_center_y = (bottom_zone_top + bottom_zone_bottom) / 2",
        "        top_center = np.array([0, top_zone_center_y, 0])",
        "        middle_center = np.array([0, middle_zone_center_y, 0])",
        "        bottom_center = np.array([0, bottom_zone_center_y, 0])",
        "",
        "        # Problem variables",
        "        h0 = 50.0",
        "        v0 = 25.0",
        "        angle_deg = -37.0 # Angle of depression",
        "        g = 10.0",
        "        ",
        "        # Calculate derived values",
        "        theta = np.radians(angle_deg)",
        "        vx = v0 * np.cos(theta)",
        "        vy0 = v0 * np.sin(theta)",
        "        ",
        "        # Using quadratic formula for t_flight: y = h0 + vy0*t - 0.5*g*t^2 = 0",
        "        # 0.5*g*t^2 - vy0*t - h0 = 0",
        "        # a = 0.5*g, b = -vy0, c = -h0",
        "        a_quad = 0.5 * g",
        "        b_quad = -vy0",
        "        c_quad = -h0",
        "        discriminant = b_quad**2 - 4 * a_quad * c_quad",
        "        t_flight = (-b_quad + np.sqrt(discriminant)) / (2 * a_quad) # Positive root",
        "",
        "        x_range_total = vx * t_flight",
        "",
        "        # --- Top Zone: Title and Problem Statement ---",
        "        title_text = Text('การเคลื่อนที่แบบโพรเจกไทล์: ปาก้อนหินมุมก้ม', font='TH Sarabun New', font_size=28, color=WHITE)",
        "        if title_text.width > frame_width * 0.88:",
        "            title_text.scale_to_fit_width(frame_width * 0.88)",
        "        if title_text.height > top_zone_height * 0.88:",
        "            title_text.scale_to_fit_height(top_zone_height * 0.88)",
        "        title_text.move_to(top_center)",
        "",
        "        problem_statement_lines = [",
        "            'ชายคนหนึ่งยืนอยู่บนดาดฟ้าตึกสูง 50 เมตร แล้วปาก้อนหินออกไป',",
        "            'ในแนวทำมุมก้ม 37 องศากับแนวระดับ ด้วยความเร็ว 25 เมตร/วินาที',",
        "            'ก. นานเท่าใดวัตถุจึงจะตกถึงพื้น',",
        "            'ข. ก้อนหินตกห่างจากตัวตึกเท่าใด'",
        "        ]",
        "        problem_statement = VGroup(*[",
        "            Text(line, font='TH Sarabun New', font_size=26, color=GRAY_A)",
        "            for line in problem_statement_lines",
        "        ]).arrange(DOWN, aligned_edge=LEFT, buff=0.1)",
        "        ",
        "        if problem_statement.width > frame_width * 0.88:",
        "            problem_statement.scale_to_fit_width(frame_width * 0.88)",
        "        if problem_statement.height > top_zone_height * 0.88:",
        "            problem_statement.scale_to_fit_height(top_zone_height * 0.88)",
        "        problem_statement.move_to(top_center + DOWN * (top_zone_height * 0.2))",
        "",
        "        # --- Middle Zone: Visualization ---",
        "        x_max_display = np.ceil(x_range_total / 10) * 10 + 10",
        "        y_max_display = np.ceil(h0 / 10) * 10 + 10",
        "        x_step = max(5, int(x_max_display / 4))",
        "        y_step = max(5, int(y_max_display / 4))",
        "",
        "        axes = Axes(",
        "            x_range=[0, x_max_display, x_step],",
        "            y_range=[0, y_max_display, y_step],",
        "            x_length=frame_width * 0.60,",
        "            y_length=middle_zone_height * 0.65,",
        "            axis_config={",
        "                'color': GRAY_C,",
        "                'stroke_width': 2,",
        "                'include_tip': True,",
        "                'tip_length': 0.15,",
        "                'tip_width': 0.10,",
        "            },",
        "            x_axis_config={'include_numbers': True, 'font_size': 16, 'color': GRAY_B, 'numbers_to_exclude': [0]},",
        "            y_axis_config={'include_numbers': True, 'font_size': 16, 'color': GRAY_B, 'numbers_to_exclude': [0]},",
        "        )",
        "        axes.shift(axes.coords_to_point(0, h0) - axes.get_origin())",
        "",
        "        x_label = axes.get_x_axis_label(",
        "            Text('ระยะทางแนวราบ (m)', font='TH Sarabun New', font_size=18, color=GRAY_A),",
        "            edge=DOWN, direction=DOWN, buff=0.35",
        "        )",
        "        y_label = axes.get_y_axis_label(",
        "            Text('ความสูง (m)', font='TH Sarabun New', font_size=18, color=GRAY_A).rotate(90 * DEGREES),",
        "            edge=LEFT, direction=LEFT, buff=0.30",
        "        )",
        "",
        "        def trajectory_func(t):",
        "            x = vx * t",
        "            y = h0 + vy0 * t - 0.5 * g * t**2",
        "            return axes.coords_to_point(x, y)",
        "",
        "        path = ParametricFunction(",
        "            lambda t: trajectory_func(t),",
        "            t_range=[0, t_flight],",
        "            color=TEAL_C,",
        "            stroke_width=4,",
        "        )",
        "",
        "        start_dot = Dot(axes.coords_to_point(0, h0), color=ORANGE, radius=0.1)",
        "        end_dot = Dot(axes.coords_to_point(x_range_total, 0), color=RED_C, radius=0.1)",
        "        ",
        "        # Initial velocity vector (at an angle)",
        "        initial_velocity_vector = Arrow(",
        "            start=start_dot.get_center(),",
        "            end=start_dot.get_center() + (RIGHT * np.cos(np.radians(abs(angle_deg))) + DOWN * np.sin(np.radians(abs(angle_deg)))) * 1.5,",
        "            buff=0, color=GREEN_C, stroke_width=4, tip_length=0.2",
        "        )",
        "        v0_label = MathTex(r'v_0 = 25\\,\\mathrm{m/s}', font_size=20, color=GREEN_C).next_to(initial_velocity_vector, UR, buff=0.1)",
        "        angle_arc = Arc(",
        "            radius=0.5,",
        "            start_angle=0,",
        "            angle=theta,",
        "            arc_center=start_dot.get_center(),",
        "            color=YELLOW_C",
        "        )",
        "        angle_label = MathTex(r'37^{\\circ}', font_size=20, color=YELLOW_C).next_to(angle_arc, DR, buff=0.1)",
        "",
        "        h0_line = DashedLine(axes.coords_to_point(0, h0), axes.coords_to_point(x_range_total, h0), color=GRAY_D, stroke_width=2)",
        "        sx_line = DashedLine(axes.coords_to_point(x_range_total, h0), axes.coords_to_point(x_range_total, 0), color=GRAY_D, stroke_width=2)",
        "",
        "        h0_label = MathTex(r'h_0 = 50\\,\\mathrm{m}', font_size=20, color=GRAY_A).next_to(h0_line, UP, buff=0.1)",
        "        sx_label = MathTex(r'S_x = ?', font_size=20, color=GRAY_A).next_to(sx_line, RIGHT, buff=0.1)",
        "",
        "        axes_group = VGroup(axes, x_label, y_label, path, start_dot, end_dot, initial_velocity_vector, v0_label, angle_arc, angle_label, h0_line, sx_line, h0_label, sx_label)",
        "        ",
        "        axes_group.scale_to_fit_width(frame_width * 0.88)",
        "        axes_group.scale_to_fit_height(middle_zone_height * 0.82)",
        "        if axes_group.width < frame_width * 0.55:",
        "            axes_group.scale(frame_width * 0.55 / axes_group.width)",
        "        if axes_group.height < middle_zone_height * 0.55:",
        "            axes_group.scale(middle_zone_height * 0.55 / axes_group.height)",
        "        axes_group.move_to(middle_center)",
        "",
        "        # --- Bottom Zone: Equations ---",
        "        # Step 1: Resolve initial velocity",
        "        step1_title = VGroup(",
        "            Text('ขั้นตอนที่ 1:', font='TH Sarabun New', font_size=26, color=GOLD_B),",
        "            Text('แตกความเร็วต้นเป็นองค์ประกอบ', font='TH Sarabun New', font_size=26, color=GOLD_B),",
        "        ).arrange(DOWN, aligned_edge=LEFT, buff=0.08)",
        "",
        "        eq1_1 = MathTex(r'v_x = v_0 \\cos\\theta = 25 \\cos 37^{\\circ}', font_size=26, color=BLUE_C)",
        "        eq1_2 = MathTex(r'v_x \\approx 25(0.7986) = 19.97\\,\\mathrm{m/s}', font_size=26, color=WHITE)",
        "        eq1_3 = MathTex(r'u_y = -v_0 \\sin\\theta = -25 \\sin 37^{\\circ}', font_size=26, color=BLUE_C)",
        "        eq1_4 = MathTex(r'u_y \\approx -25(0.6018) = -15.05\\,\\mathrm{m/s}', font_size=26, color=WHITE)",
        "        ",
        "        step1_group = VGroup(step1_title, eq1_1, eq1_2, eq1_3, eq1_4).arrange(DOWN, aligned_edge=LEFT, buff=0.25)",
        "        step1_group.scale_to_fit_width(frame_width * 0.88)",
        "        step1_group.scale_to_fit_height(bottom_zone_height * 0.88)",
        "        step1_group.move_to(bottom_center)",
        "",
        "        # Step 2: Find time of flight",
        "        step2_title = VGroup(",
        "            Text('ขั้นตอนที่ 2:', font='TH Sarabun New', font_size=26, color=GOLD_B),",
        "            Text('หาเวลาที่ก้อนหินตกถึงพื้น', font='TH Sarabun New', font_size=26, color=GOLD_B),",
        "        ).arrange(DOWN, aligned_edge=LEFT, buff=0.08)",
        "",
        "        eq2_1 = MathTex(r'S_y = u_y t + \\frac{1}{2}gt^2', font_size=26, color=BLUE_C)",
        "        eq2_2 = MathTex(r'0 = 50 + (-15.05)t - \\frac{1}{2}(10)t^2', font_size=26, color=WHITE)",
        "        eq2_3 = MathTex(r'5t^2 + 15.05t - 50 = 0', font_size=26, color=WHITE)",
        "        eq2_4 = MathTex(r't = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}', font_size=26, color=BLUE_C)",
        "        eq2_5 = MathTex(r't = \\frac{-15.05 + \\sqrt{(15.05)^2 - 4(5)(-50)}}{2(5)}', font_size=26, color=WHITE)",
        "        eq2_6 = MathTex(r't \\approx 2.00\\,\\mathrm{วินาที}', font_size=26, color=GREEN_C)",
        "        ",
        "        step2_group = VGroup(step2_title, eq2_1, eq2_2, eq2_3, eq2_4, eq2_5, eq2_6).arrange(DOWN, aligned_edge=LEFT, buff=0.25)",
        "        step2_group.scale_to_fit_width(frame_width * 0.88)",
        "        step2_group.scale_to_fit_height(bottom_zone_height * 0.88)",
        "        step2_group.move_to(bottom_center)",
        "",
        "        # Step 3: Find horizontal distance",
        "        step3_title = VGroup(",
        "            Text('ขั้นตอนที่ 3:', font='TH Sarabun New', font_size=26, color=GOLD_B),",
        "            Text('หาระยะทางที่ก้อนหินตกห่างจากตัวตึก', font='TH Sarabun New', font_size=26, color=GOLD_B),",
        "        ).arrange(DOWN, aligned_edge=LEFT, buff=0.08)",
        "",
        "        eq3_1 = MathTex(r'S_x = v_x t', font_size=26, color=BLUE_C)",
        "        eq3_2 = MathTex(r'S_x = (19.97)(2.00)', font_size=26, color=WHITE)",
        "        eq3_3 = MathTex(r'S_x \\approx 39.94\\,\\mathrm{เมตร}', font_size=26, color=GREEN_C)",
        "",
        "        step3_group = VGroup(step3_title, eq3_1, eq3_2, eq3_3).arrange(DOWN, aligned_edge=LEFT, buff=0.25)",
        "        step3_group.scale_to_fit_width(frame_width * 0.88)",
        "        step3_group.scale_to_fit_height(bottom_zone_height * 0.88)",
        "        step3_group.move_to(bottom_center)",
        "",
        "        # --- Animations ---",
        "        # Hook/Problem (0.0s - 11.75s)",
        "        self.play(Write(title_text), FadeIn(problem_statement), run_time=11.75)",
        "        self.wait(0.5)",
        "",
        "        # Diagram Explain (12.25s - 22.83s)",
        "        self.play(Create(axes), Create(x_label), Create(y_label), Create(h0_line), Create(sx_line), FadeIn(h0_label), FadeIn(sx_label), run_time=4.23)",
        "        self.play(GrowFromCenter(start_dot), Create(initial_velocity_vector), FadeIn(v0_label), Create(angle_arc), FadeIn(angle_label), Create(path), GrowFromCenter(end_dot), run_time=6.35)",
        "        self.wait(0.8)",
        "",
        "        # Step 1 Solve (23.63s - 28.96s)",
        "        self.play(FadeOut(problem_statement, shift=DOWN*0.1), FadeIn(step1_group[0]), run_time=2.66)",
        "        self.play(Write(step1_group[1]), run_time=1.33)",
        "        self.wait(0.8)",
        "        # (29.76s - 35.83s)",
        "        self.play(Write(step1_group[2]), run_time=6.07)",
        "        self.wait(0.8)",
        "        # (36.63s - 46.05s)",
        "        self.play(Write(step1_group[3]), run_time=4.71)",
        "        self.play(Write(step1_group[4]), run_time=4.71)",
        "        self.wait(0.8)",
        "",
        "        # Step 2 Solve (46.85s - 52.0s)",
        "        self.play(Transform(step1_group, step2_group), run_time=5.15)",
        "        self.wait(0.8)",
        "        # (52.8s - 57.72s)",
        "        self.play(Write(step2_group[1]), run_time=4.92)",
        "        self.wait(0.8)",
        "        # (58.52s - 63.77s)",
        "        self.play(Write(step2_group[2]), run_time=5.25)",
        "        self.wait(0.8)",
        "        # (64.57s - 69.82s)",
        "        self.play(Write(step2_group[3]), run_time=5.25)",
        "        self.wait(0.8)",
        "        # (70.62s - 73.62s)",
        "        self.play(Write(step2_group[4]), run_time=3.0)",
        "        self.wait(0.8)",
        "        # (74.42s - 76.25s)",
        "        self.play(Write(step2_group[5]), run_time=1.83)",
        "        self.wait(0.8)",
        "        # (77.05s - 80.69s)",
        "        self.play(Write(step2_group[6]), run_time=3.64)",
        "        self.wait(0.8)",
        "",
        "        # Step 3 Solve (81.49s - 86.82s)",
        "        self.play(Transform(step2_group, step3_group), run_time=5.33)",
        "        self.wait(0.8)",
        "        # (87.62s - 90.62s)",
        "        self.play(Write(step3_group[1]), run_time=3.0)",
        "        self.wait(0.8)",
        "        # (91.42s - 95.34s)",
        "        self.play(Write(step3_group[2]), run_time=3.92)",
        "        self.wait(0.8)",
        "        # (96.14s - 99.97s)",
        "        self.play(Write(step3_group[3]), run_time=3.83)",
        "        self.wait(0.8)",
        "",
        "        # CTA (100.77s - 110.11s)",
        "        self.play(FadeOut(step3_group, shift=DOWN*0.1), FadeOut(title_text, shift=UP*0.1), run_time=9.34)",
        "        self.wait(0.5)"
      ]
}

if __name__ == "__main__":
    engine = Manim_Engine(output_dir="renders")
    result = engine.render_episode(sample_episode)
    print(result)

    if result["status"] == "success":
        # Uncomment once firebase_client.py has a real service account key configured
        # from app.storage.video_storage import upload_manim_render
        # upload_manim_render(uid="test-uid-123", episode_number=1)
        pass