"""
Manual test script: render one Manim episode from a hardcoded JSON
payload and (optionally) upload the result to Firebase.

This is NOT part of the FastAPI app -- run it directly:
    python scripts/test_manim_render.py

It exists so you can verify Manim output looks right before wiring
the orchestrator -> manim_engine -> video_storage chain together.
"""

import sys
import os

# allow `from app.services... import ...` when running this script directly
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.services.manim_engine import Manim_Engine

# Replace with a real Production Plan episode once your orchestrator exists.
# For now, hand-write one to confirm Manim itself renders correctly.
sample_episode = {
      "episode_number": 2,
      "title": "ความเร็วระเบิดตอนตกถึงพื้น (ตอนที่ 2)",
      "core_vocabulary": [
        "ความเร็วแนวราบ",
        "ความเร็วแนวดิ่ง",
        "ความเร็วลัพธ์",
        "เวกเตอร์",
        "ทฤษฎีบทพีทาโกรัส"
      ],
      "video_plan": {
        "estimated_duration_seconds": 100,
        "visual_cues": "แสดงโจทย์ปัญหา (ส่วน ข), แสดงค่าที่คำนวณได้จากตอนที่แล้ว, สร้างระบบแกนพิกัดพร้อมเส้นทางโพรเจกไทล์, แสดงสมการและขั้นตอนการคำนวณหาความเร็วแนวราบสุดท้าย, แสดงสมการและขั้นตอนการคำนวณหาความเร็วแนวดิ่งสุดท้าย, แสดงเวกเตอร์ความเร็วแนวราบและแนวดิ่งที่จุดตกกระทบ, แสดงสมการและขั้นตอนการคำนวณหาความเร็วลัพธ์, แสดงเวกเตอร์ความเร็วลัพธ์",
        "audio_cues": "เสียงบรรยายโจทย์, เสียงทบทวนค่าจากตอนที่แล้ว, เสียงอธิบายการเคลื่อนที่ของระเบิด, เสียงอธิบายขั้นตอนการคำนวณความเร็วแต่ละแนว, เสียงอธิบายการรวมเวกเตอร์ความเร็ว, สรุปผลลัพธ์"
      },
      "script": {
        "hook": "ในตอนที่แล้ว เราคำนวณได้แล้วว่าระเบิดใช้เวลา 20 วินาที และตกไกล 4000 เมตร",
        "main_body": "ตอนนี้เราจะมาหาความเร็วของระเบิดตอนที่มันกระทบพื้นกัน! ความเร็วนี้ไม่ใช่แค่ความเร็วในแนวราบหรือแนวดิ่งอย่างเดียว แต่เป็นความเร็วลัพธ์ที่เป็นเวกเตอร์",
        "example_or_trick": "ความเร็วในแนวราบจะคงที่ตลอดการเคลื่อนที่ แต่ความเร็วในแนวดิ่งจะเพิ่มขึ้นเรื่อยๆ เพราะแรงโน้มถ่วง! เราจะหาความเร็วแนวดิ่งตอนกระทบพื้น แล้วนำความเร็วทั้งสองแนวมาหาความเร็วลัพธ์ด้วยทฤษฎีบทพีทาโกรัส",
        "call_to_action": "มาดูกันว่าระเบิดจะพุ่งชนพื้นด้วยความเร็วเท่าไหร่!"
      },
      "manim_code_lines": [
        "from manim import *",
        "",
        "class ProjectileProblem3Episode2(Scene):",
        "    def construct(self):",
        "        # --- Screen Zoning Setup (CRITICAL) ---",
        "        frame_height = config.frame_height",
        "        frame_width = config.frame_width",
        "",
        "        top_zone_height = frame_height * 0.18",
        "        bottom_zone_height = frame_height * 0.28",
        "        middle_zone_height = frame_height - top_zone_height - bottom_zone_height",
        "",
        "        top_zone_top = frame_height / 2",
        "        top_zone_bottom = top_zone_top - top_zone_height",
        "        top_zone_center = (top_zone_top + top_zone_bottom) / 2",
        "",
        "        bottom_zone_bottom = -frame_height / 2",
        "        bottom_zone_top = bottom_zone_bottom + bottom_zone_height",
        "        bottom_zone_center = (bottom_zone_top + bottom_zone_bottom) / 2",
        "",
        "        middle_zone_top = top_zone_bottom",
        "        middle_zone_bottom = bottom_zone_top",
        "        middle_zone_center = (middle_zone_top + middle_zone_bottom) / 2",
        "",
        "        middle_zone_safe_width = frame_width * 0.9",
        "        middle_zone_safe_height = middle_zone_height * 0.9",
        "",
        "        # --- Problem Statement (Top Zone) ---",
        "        problem_text_str = '3. เครื่องบินทิ้งระเบิด บินในแนวระดับด้วยความเร็ว 200 เมตร/วินาที และสูงจากพื้นดิน 2000 เมตร เมื่อทิ้งระเบิดที่ปีกเครื่องบินลงมา จงหา ข. ระเบิดกระทบพื้นดินด้วยอัตราเร็วเท่าใด'",
        "        problem_text = Text(problem_text_str, font='TH Sarabun New', color=WHITE, disable_ligatures=True)",
        "        problem_text.scale_to_fit_width(frame_width * 0.9)",
        "        if problem_text.height > top_zone_height * 0.8:",
        "            problem_text.scale_to_fit_height(top_zone_height * 0.8)",
        "        problem_text.move_to(top_zone_center)",
        "        self.play(Write(problem_text))",
        "        self.wait(1)",
        "",
        "        # --- Recall values (Bottom Zone) ---",
        "        t_val = 20",
        "        u_x_val = 200",
        "        s_y_val = 2000",
        "        g_val = 10",
        "",
        "        recall_title = Text('ค่าที่คำนวณได้จากตอนที่แล้ว:', font='TH Sarabun New', color=YELLOW).scale(0.7)",
        "        recall_title.move_to(bottom_zone_top - recall_title.height/2 - 0.2 * frame_height)",
        "        ",
        "        recall_t = MathTex(r't = 20 \\mathrm{\\,s}', color=WHITE).scale(0.65)",
        "        recall_ux = MathTex(r'u_x = 200 \\mathrm{\\,m/s}', color=BLUE).scale(0.65)",
        "",
        "        recall_group = VGroup(recall_t, recall_ux).arrange(DOWN, aligned_edge=LEFT, buff=0.2)",
        "        recall_group.move_to(bottom_zone_center + LEFT * frame_width * 0.25)",
        "",
        "        self.play(Write(recall_title), FadeIn(recall_group))",
        "        self.wait(1)",
        "",
        "        # --- Axes and Projectile Animation (Middle Zone) ---",
        "        x_max_plot = u_x_val * t_val * 1.2",
        "        y_max_plot = s_y_val * 1.2",
        "",
        "        axes = Axes(",
        "            x_range=[0, x_max_plot, 1000],",
        "            y_range=[0, y_max_plot, 500],",
        "            x_length=middle_zone_safe_width * 0.8,",
        "            y_length=middle_zone_safe_height * 0.8,",
        "            axis_config={'include_numbers': True, 'font_size': 24}",
        "        )",
        "        axes.move_to(middle_zone_center)",
        "",
        "        x_label = axes.get_x_axis_label(Text('ระยะทางแนวราบ (m)', font='TH Sarabun New', color=WHITE).scale(0.5))",
        "        y_label = axes.get_y_axis_label(Text('ความสูง (m)', font='TH Sarabun New', color=WHITE).scale(0.5))",
        "        axes_labels = VGroup(x_label, y_label)",
        "",
        "        self.play(Create(axes), Write(axes_labels))",
        "        self.wait(0.5)",
        "",
        "        # Projectile path function",
        "        def get_projectile_point(t):",
        "            x_coord = u_x_val * t",
        "            y_coord = s_y_val - 0.5 * g_val * t**2",
        "            return axes.c2p(x_coord, y_coord)",
        "",
        "        projectile_path = ParametricFunction(",
        "            get_projectile_point,",
        "            t_range=[0, t_val, 0.01],",
        "            color=YELLOW",
        "        )",
        "        self.play(Create(projectile_path), run_time=2)",
        "        self.wait(0.5)",
        "",
        "        # Landing point",
        "        landing_point_coords = axes.c2p(u_x_val * t_val, 0)",
        "        dot_landing = Dot(landing_point_coords, color=YELLOW, radius=0.1)",
        "        self.play(FadeIn(dot_landing))",
        "        self.wait(0.5)",
        "",
        "        # --- Calculations for final velocity (Bottom Zone) ---",
        "        self.play(FadeOut(recall_group), FadeOut(recall_title))",
        "",
        "        calc_title_3 = Text('ขั้นตอนการคำนวณความเร็วสุดท้าย:', font='TH Sarabun New', color=YELLOW).scale(0.7)",
        "        calc_title_3.move_to(bottom_zone_top - calc_title_3.height/2 - 0.2 * frame_height)",
        "        self.play(Write(calc_title_3))",
        "",
        "        # Step 1: Find final horizontal velocity (v_x)",
        "        step1_text_v = Text('1. หาความเร็วแนวราบสุดท้าย (v_x):', font='TH Sarabun New', color=WHITE).scale(0.6)",
        "        eq_vx_general = MathTex(r'v_x = u_x', color=WHITE).scale(0.7)",
        "        eq_vx_final = MathTex(r'v_x = 200 \\mathrm{\\,m/s}', color=BLUE).scale(0.7)",
        "",
        "        calc_group_3 = VGroup(step1_text_v, eq_vx_general, eq_vx_final).arrange(DOWN, aligned_edge=LEFT, buff=0.2)",
        "        calc_group_3.move_to(bottom_zone_center + LEFT * frame_width * 0.25)",
        "",
        "        self.play(FadeIn(step1_text_v))",
        "        self.play(Write(eq_vx_general))",
        "        self.play(TransformMatchingTex(eq_vx_general, eq_vx_final))",
        "        self.wait(1)",
        "",
        "        # Step 2: Find final vertical velocity (v_y)",
        "        self.play(FadeOut(calc_group_3))",
        "",
        "        step2_text_v = Text('2. หาความเร็วแนวดิ่งสุดท้าย (v_y):', font='TH Sarabun New', color=WHITE).scale(0.6)",
        "        eq_vy_general = MathTex(r'v_y = u_y + gt', color=WHITE).scale(0.7)",
        "        eq_vy_sub = MathTex(r'v_y = 0 + (10)(20)', color=WHITE).scale(0.7)",
        "        eq_vy_final = MathTex(r'v_y = 200 \\mathrm{\\,m/s}', color=RED).scale(0.7)",
        "",
        "        calc_group_4 = VGroup(step2_text_v, eq_vy_general, eq_vy_sub, eq_vy_final).arrange(DOWN, aligned_edge=LEFT, buff=0.2)",
        "        calc_group_4.move_to(bottom_zone_center + LEFT * frame_width * 0.25)",
        "",
        "        self.play(FadeIn(step2_text_v))",
        "        self.play(Write(eq_vy_general))",
        "        self.play(TransformMatchingTex(eq_vy_general, eq_vy_sub))",
        "        self.play(TransformMatchingTex(eq_vy_sub, eq_vy_final))",
        "        self.wait(1)",
        "",
        "        # --- Display Velocity Vectors on Graph ---",
        "        vx_arrow = Arrow(start=landing_point_coords, end=landing_point_coords + RIGHT * 1.5, buff=0, color=BLUE, max_stroke_width_to_length_ratio=0.05, max_tip_length_to_length_ratio=0.25)",
        "        vx_label = MathTex(r'v_x = 200 \\mathrm{\\,m/s}', color=BLUE).scale(0.6).next_to(vx_arrow, UP, buff=0.1)",
        "        self.play(Create(vx_arrow), Write(vx_label))",
        "        self.wait(0.5)",
        "",
        "        vy_arrow = Arrow(start=landing_point_coords, end=landing_point_coords + DOWN * 1.5, buff=0, color=RED, max_stroke_width_to_length_ratio=0.05, max_tip_length_to_length_ratio=0.25)",
        "        vy_label = MathTex(r'v_y = 200 \\mathrm{\\,m/s}', color=RED).scale(0.6).next_to(vy_arrow, RIGHT, buff=0.1)",
        "        self.play(Create(vy_arrow), Write(vy_label))",
        "        self.wait(0.5)",
        "",
        "        # Step 3: Find resultant velocity (V)",
        "        self.play(FadeOut(calc_group_4))",
        "",
        "        step3_text_v = Text('3. หาความเร็วลัพธ์ (V):', font='TH Sarabun New', color=WHITE).scale(0.6)",
        "        eq_V_general = MathTex(r'V = \\sqrt{v_x^2 + v_y^2}', color=WHITE).scale(0.7)",
        "        eq_V_sub = MathTex(r'V = \\sqrt{(200)^2 + (200)^2}', color=WHITE).scale(0.7)",
        "        eq_V_simplify = MathTex(r'V = \\sqrt{2 \\cdot (200)^2}', color=WHITE).scale(0.7)",
        "        eq_V_final = MathTex(r'V = 200\\sqrt{2} \\mathrm{\\,m/s}', color=WHITE).scale(0.7)",
        "        eq_V_approx = MathTex(r'V \\approx 282.84 \\mathrm{\\,m/s}', color=WHITE).scale(0.7)",
        "",
        "        calc_group_5 = VGroup(step3_text_v, eq_V_general, eq_V_sub, eq_V_simplify, eq_V_final, eq_V_approx).arrange(DOWN, aligned_edge=LEFT, buff=0.2)",
        "        calc_group_5.move_to(bottom_zone_center + LEFT * frame_width * 0.25)",
        "",
        "        self.play(FadeIn(step3_text_v))",
        "        self.play(Write(eq_V_general))",
        "        self.play(TransformMatchingTex(eq_V_general, eq_V_sub))",
        "        self.play(TransformMatchingTex(eq_V_sub, eq_V_simplify))",
        "        self.play(TransformMatchingTex(eq_V_simplify, eq_V_final))",
        "        self.play(TransformMatchingTex(eq_V_final, eq_V_approx))",
        "        self.wait(1)",
        "",
        "        # Resultant V vector",
        "        V_arrow = Arrow(start=landing_point_coords, end=landing_point_coords + RIGHT * 1.5 + DOWN * 1.5, buff=0, color=GOLD, max_stroke_width_to_length_ratio=0.05, max_tip_length_to_length_ratio=0.25)",
        "        V_label = MathTex(r'V = 200\\sqrt{2} \\mathrm{\\,m/s}', color=GOLD).scale(0.6).next_to(V_arrow, DR, buff=0.1)",
        "        self.play(Create(V_arrow), Write(V_label))",
        "        self.wait(2)",
        "",
        "        # Final fade out",
        "        self.play(FadeOut(problem_text), FadeOut(calc_group_5), FadeOut(calc_title_3),",
        "                  FadeOut(axes), FadeOut(axes_labels), FadeOut(projectile_path), FadeOut(dot_landing),",
        "                  FadeOut(vx_arrow), FadeOut(vx_label), FadeOut(vy_arrow), FadeOut(vy_label),",
        "                  FadeOut(V_arrow), FadeOut(V_label))",
        "        self.wait(1)"
      ]
}

if __name__ == "__main__":
    engine = Manim_Engine(output_dir="renders")
    result = engine.render_episode(sample_episode)
    print(result)

    if result["status"] == "success":
        # Uncomment once firebase_client.py has a real service account key configured
        # from app.storage.video_storage import upload_manim_render
        # upload_manim_render(uid="test-uid-123", episode_number=1)
        pass