"""
Manual test script: render one Manim episode from a hardcoded JSON
payload and (optionally) upload the result to Firebase.

This is NOT part of the FastAPI app -- run it directly:
    python scripts/test_manim_render.py

It exists so you can verify Manim output looks right before wiring
the orchestrator -> manim_engine -> video_storage chain together.
"""

import sys
import os

# allow `from app.services... import ...` when running this script directly
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.services.manim_engine import Manim_Engine

# Replace with a real Production Plan episode once your orchestrator exists.
# For now, hand-write one to confirm Manim itself renders correctly.
sample_episode = {
      "episode_number": 1,
      "title": "การเคลื่อนที่แบบโพรเจกไทล์: ขว้างหินจากตึก",
      "core_vocabulary": [
        "การเคลื่อนที่แบบโพรเจกไทล์",
        "ความเร็วต้น",
        "มุมก้ม",
        "ระยะทางแนวราบ",
        "เวลา",
        "แรงโน้มถ่วง"
      ],
      "video_plan": {
        "estimated_duration_seconds": 65,
        "visual_cues": "แสดงโจทย์, กราฟการเคลื่อนที่แบบโพรเจกไทล์, เวกเตอร์ความเร็วต้น, จุดเริ่มต้นและจุดตก, เส้นประแสดงความสูงและระยะตกในแนวราบ, ขั้นตอนการคำนวณสมการหาเวลาและระยะทาง",
        "audio_cues": "เสียงพากย์อธิบายโจทย์, อธิบายภาพกราฟ, อธิบายแต่ละขั้นตอนการคำนวณอย่างละเอียด"
      },
      "script": {
        "hook": "เคยสงสัยไหมว่าถ้าเราปาของลงมาจากตึกสูงๆ โดยทำมุมก้ม ของสิ่งนั้นจะใช้เวลานานเท่าไหร่กว่าจะตกถึงพื้น และจะตกห่างจากตัวตึกไปเท่าไหร่? วันนี้เราจะมาหาคำตอบกัน!",
        "main_body": "โจทย์ข้อนี้เป็นเรื่องการเคลื่อนที่แบบโพรเจกไทล์ ที่วัตถุมีความเร็วต้นทั้งในแนวราบและแนวดิ่ง และอยู่ภายใต้แรงโน้มถ่วงในแนวดิ่งเท่านั้น เราจะแบ่งการวิเคราะห์ออกเป็นสองส่วนคือ การเคลื่อนที่ในแนวดิ่งเพื่อหาเวลา และการเคลื่อนที่ในแนวราบเพื่อหาระยะทาง",
        "example_or_trick": "เคล็ดลับสำคัญคือการแยกวิเคราะห์การเคลื่อนที่ในแนวแกน X และแกน Y อย่างอิสระ โดยที่เวลาเป็นตัวเชื่อมโยงทั้งสองแกนเข้าด้วยกัน และอย่าลืมว่ามุมก้มจะทำให้ความเร็วต้นในแนวดิ่งมีทิศลง ซึ่งเราจะกำหนดให้เป็นค่าลบ",
        "call_to_action": "การเข้าใจการเคลื่อนที่แบบโพรเจกไทล์เป็นพื้นฐานสำคัญในฟิสิกส์ ลองฝึกทำโจทย์ลักษณะนี้เพิ่มเติมเพื่อความเข้าใจที่ลึกซึ้งยิ่งขึ้นนะครับ!"
      },
      "voiceover_script": [
        {
          "segment_id": "ep1_seg01",
          "phase": "hook_problem",
          "thai_text": "เคยสงสัยไหมว่าถ้าเราปาของลงมาจากตึกสูงๆ โดยทำมุมก้ม ของสิ่งนั้นจะใช้เวลานานเท่าไหร่กว่าจะตกถึงพื้น และจะตกห่างจากตัวตึกไปเท่าไหร่? วันนี้เราจะมาหาคำตอบจากโจทย์ข้อนี้กันครับ",
          "start_time_seconds": 0.0,
          "end_time_seconds": 10.0,
          "start_frame": 0,
          "end_frame": 600,
          "synced_visual_action": "FadeIn(problem_text) ที่เวลา 0.0 วินาที"
        },
        {
          "segment_id": "ep1_seg02",
          "phase": "diagram_explain",
          "thai_text": "จากโจทย์ ชายคนหนึ่งยืนอยู่บนดาดฟ้าตึกสูง ห้าสิบ เมตร แล้วปาหินออกไปในแนวทำมุมก้ม สามสิบเจ็ด องศา กับแนวระดับ ด้วยความเร็ว ยี่สิบห้า เมตรต่อวินาที เราสามารถวาดภาพการเคลื่อนที่ของก้อนหินได้ดังนี้ครับ จะเห็นว่าก้อนหินจะเคลื่อนที่เป็นเส้นโค้งพาราโบลาลงมา",
          "start_time_seconds": 10.0,
          "end_time_seconds": 22.5,
          "start_frame": 600,
          "end_frame": 1350,
          "synced_visual_action": "Create(axes_group) และแสดงวิถีการเคลื่อนที่ของก้อนหิน พร้อมจุดเริ่มต้น จุดตก และเวกเตอร์ความเร็วต้น ที่เวลา 10.0 วินาที"
        },
        {
          "segment_id": "ep1_seg03",
          "phase": "step_solve",
          "thai_text": "ก่อนอื่น เรามาแยกองค์ประกอบความเร็วต้นกันก่อนครับ ความเร็วต้นในแนวราบ วีเอ็กซ์ เท่ากับ วีศูนย์ โคไซน์ ทีต้า ซึ่งเท่ากับ ยี่สิบห้า คูณ โคไซน์ ของ ลบสามสิบเจ็ด องศา ได้ประมาณ สิบเก้าจุดเก้าเจ็ด เมตรต่อวินาที ส่วนความเร็วต้นในแนวดิ่ง วีวายศูนย์ เท่ากับ วีศูนย์ ไซน์ ทีต้า ซึ่งเท่ากับ ยี่สิบห้า คูณ ไซน์ ของ ลบสามสิบเจ็ด องศา ได้ประมาณ ลบสิบห้าจุดศูนย์ห้า เมตรต่อวินาที โดยเครื่องหมายลบแสดงว่ามีทิศพุ่งลง",
          "start_time_seconds": 22.5,
          "end_time_seconds": 38.0,
          "start_frame": 1350,
          "end_frame": 2280,
          "synced_visual_action": "FadeIn(step_group_1) แสดงการคำนวณองค์ประกอบความเร็วต้น ที่เวลา 22.5 วินาที"
        },
        {
          "segment_id": "ep1_seg04",
          "phase": "step_solve",
          "thai_text": "ขั้นตอนแรก เราจะหาเวลาที่วัตถุตกถึงพื้น โดยพิจารณาการเคลื่อนที่ในแนวดิ่ง ใช้สมการ เอสวาย เท่ากับ วีวายศูนย์ที บวก หนึ่งส่วนสอง จีที กำลังสอง โดยให้ทิศลงเป็นบวก ความสูงตึก ห้าสิบ เมตร ความเร็วต้นแนวดิ่ง ลบสิบห้าจุดศูนย์ห้า เมตรต่อวินาที และค่า จี เท่ากับ สิบ เมตรต่อวินาทีกำลังสอง เมื่อแทนค่าและแก้สมการกำลังสอง เราจะได้เวลา ที เท่ากับ ห้าจุดศูนย์หนึ่ง วินาที",
          "start_time_seconds": 38.0,
          "end_time_seconds": 52.0,
          "start_frame": 2280,
          "end_frame": 3120,
          "synced_visual_action": "FadeOut(step_group_1) และ FadeIn(step_group_2) แสดงการคำนวณหาเวลาตกถึงพื้น ที่เวลา 38.0 วินาที"
        },
        {
          "segment_id": "ep1_seg05",
          "phase": "step_solve",
          "thai_text": "ขั้นตอนที่สอง เราจะหาระยะทางที่ก้อนหินตกห่างจากตัวตึกในแนวราบ โดยพิจารณาการเคลื่อนที่ในแนวราบ ซึ่งมีความเร็วคงที่ ใช้สมการ เอสเอ็กซ์ เท่ากับ วีเอ็กซ์ที แทนค่า วีเอ็กซ์ ประมาณ สิบเก้าจุดเก้าเจ็ด เมตรต่อวินาที และเวลา ที ห้าจุดศูนย์หนึ่ง วินาที ที่เราคำนวณได้จากขั้นตอนแรก จะได้ระยะทาง เอสเอ็กซ์ ประมาณ หนึ่งร้อย เมตรพอดีครับ",
          "start_time_seconds": 52.0,
          "end_time_seconds": 62.0,
          "start_frame": 3120,
          "end_frame": 3720,
          "synced_visual_action": "FadeOut(step_group_2) และ FadeIn(step_group_3) แสดงการคำนวณหาระยะทางแนวราบ ที่เวลา 52.0 วินาที"
        },
        {
          "segment_id": "ep1_seg06",
          "phase": "cta",
          "thai_text": "เห็นไหมครับว่าการแยกวิเคราะห์การเคลื่อนที่ในแต่ละแกนช่วยให้เราแก้โจทย์โพรเจกไทล์ได้อย่างเป็นระบบ ลองฝึกทำโจทย์ลักษณะนี้เพิ่มเติมเพื่อความเข้าใจที่ลึกซึ้งยิ่งขึ้นนะครับ!",
          "start_time_seconds": 62.0,
          "end_time_seconds": 67.0,
          "start_frame": 3720,
          "end_frame": 4020,
          "synced_visual_action": "FadeOut(step_group_3) และ FadeIn(cta_text) ที่เวลา 62.0 วินาที"
        }
      ],
      "manim_code_lines": [
        "import numpy as np",
        "from manim import *",
        "",
        "config.pixel_width = 1080",
        "config.pixel_height = 1920",
        "config.frame_height = 16.0",
        "config.frame_width = 9.0",
        "config.frame_rate = 60",
        "",
        "class PhysicsScene(Scene):",
        "    def construct(self):",
        "        self.camera.background_color = '#1C1C2E'",
        "        frame_height = config.frame_height",
        "        frame_width = config.frame_width",
        "        top_zone_height = frame_height * 0.20",
        "        middle_zone_height = frame_height * 0.45",
        "        bottom_zone_height = frame_height * 0.35",
        "        top_zone_top = frame_height / 2",
        "        top_zone_bottom = top_zone_top - top_zone_height",
        "        top_zone_center_y = (top_zone_top + top_zone_bottom) / 2",
        "        middle_zone_top = top_zone_bottom",
        "        middle_zone_bottom = middle_zone_top - middle_zone_height",
        "        middle_zone_center_y = (middle_zone_top + middle_zone_bottom) / 2",
        "        bottom_zone_top = middle_zone_bottom",
        "        bottom_zone_bottom = bottom_zone_top - bottom_zone_height",
        "        bottom_zone_center_y = (bottom_zone_top + bottom_zone_bottom) / 2",
        "        top_center = np.array([0, top_zone_center_y, 0])",
        "        middle_center = np.array([0, middle_zone_center_y, 0])",
        "        bottom_center = np.array([0, bottom_zone_center_y, 0])",
        "",
        "        # --- Problem Parameters ---",
        "        g = 10.0  # m/s^2",
        "        h0 = 50.0 # m (initial height)",
        "        v0 = 25.0 # m/s (initial speed)",
        "        angle_deg = -37.0 # degrees (downwards from horizontal)",
        "",
        "        theta = np.radians(angle_deg)",
        "        vx = v0 * np.cos(theta)",
        "        vy0 = v0 * np.sin(theta) # This will be negative",
        "",
        "        # Calculate time of flight (t_flight) using quadratic formula for y = 0",
        "        # 0 = h0 + vy0*t - 0.5*g*t**2  =>  0.5*g*t**2 - vy0*t - h0 = 0",
        "        a_quad = 0.5 * g",
        "        b_quad = -vy0",
        "        c_quad = -h0",
        "        discriminant = b_quad**2 - 4 * a_quad * c_quad",
        "        t_flight = (-b_quad + np.sqrt(discriminant)) / (2 * a_quad) # Take positive root",
        "",
        "        # Calculate total horizontal range (x_range_total)",
        "        x_range_total = vx * t_flight",
        "",
        "        # --- Rounded values for display ---",
        "        vx_rounded = 19.97",
        "        vy0_rounded = -15.05",
        "        t_flight_rounded = 5.01",
        "        x_range_total_rounded = 100.0",
        "",
        "        # --- Axes Configuration ---",
        "        x_max_val = x_range_total",
        "        y_max_val = h0",
        "",
        "        # Ensure nice tick steps and fit within 5 ticks",
        "        x_axis_end = np.ceil(x_max_val / 20) * 20",
        "        if x_axis_end / 20 > 5 or x_axis_end == 0: # If more than 5 ticks with step 20, or zero range",
        "            x_axis_end = np.ceil(x_max_val / 30) * 30",
        "            x_step = 30",
        "        else:",
        "            x_step = 20",
        "        if x_axis_end == 0: x_axis_end = 10 # Avoid zero range for x if x_max_val is very small",
        "        if x_step == 0: x_step = 10",
        "",
        "        y_axis_end = np.ceil(y_max_val / 10) * 10",
        "        if y_axis_end / 10 > 5 or y_axis_end == 0: # If more than 5 ticks with step 10, or zero range",
        "            y_axis_end = np.ceil(y_max_val / 15) * 15",
        "            y_step = 15",
        "        else:",
        "            y_step = 10",
        "        if y_axis_end == 0: y_axis_end = 10 # Avoid zero range for y if y_max_val is very small",
        "        if y_step == 0: y_step = 10",
        "",
        "        # --- Scene Elements ---",
        "        # Problem Text (Top Zone)",
        "        problem_text_line1 = Text('ชายคนหนึ่งยืนอยู่บนดาดฟ้าตึกสูง 50 เมตร แล้วปาหินก้อนหินออกไป', font='TH Sarabun New', font_size=28, color=WHITE)",
        "        problem_text_line2 = Text('ในแนวทำมุมก้ม 37 องศากับแนวระดับ ด้วยความเร็ว 25 เมตร/วินาที', font='TH Sarabun New', font_size=28, color=WHITE)",
        "        problem_text_line3 = Text('ก. นานเท่าใดวัตถุจึงจะตกถึงพื้น  ข. ก้อนหินตกห่างจากตัวตึกเท่าใด', font='TH Sarabun New', font_size=28, color=WHITE)",
        "        problem_text = VGroup(problem_text_line1, problem_text_line2, problem_text_line3).arrange(DOWN, aligned_edge=LEFT, buff=0.1)",
        "        if problem_text.width > frame_width * 0.88:",
        "            problem_text.scale_to_fit_width(frame_width * 0.88)",
        "        if problem_text.height > top_zone_height * 0.88:",
        "            problem_text.scale_to_fit_height(top_zone_height * 0.88)",
        "        problem_text.move_to(top_center)",
        "",
        "        # Axes (Middle Zone)",
        "        axes = Axes(",
        "            x_range=[0, x_axis_end, x_step],",
        "            y_range=[0, y_axis_end, y_step],",
        "            x_length=frame_width * 0.60,",
        "            y_length=middle_zone_height * 0.65,",
        "            axis_config={",
        "                'color': GRAY_C,",
        "                'stroke_width': 2,",
        "                'include_tip': True,",
        "                'tip_length': 0.15,",
        "                'tip_width': 0.10,",
        "            },",
        "            x_axis_config={'include_numbers': True, 'font_size': 16, 'color': GRAY_B},",
        "            y_axis_config={'include_numbers': True, 'font_size': 16, 'color': GRAY_B},",
        "        )",
        "        x_label = axes.get_x_axis_label(",
        "            Text('ระยะทางแนวราบ (m)', font='TH Sarabun New', font_size=18, color=GRAY_A),",
        "            edge=DOWN, direction=DOWN, buff=0.35",
        "        )",
        "        y_label = axes.get_y_axis_label(",
        "            Text('ความสูง (m)', font='TH Sarabun New', font_size=18, color=GRAY_A).rotate(90 * DEGREES),",
        "            edge=LEFT, direction=LEFT, buff=0.30",
        "        )",
        "",
        "        # Trajectory path",
        "        def trajectory(t):",
        "            x = vx * t",
        "            y = h0 + vy0 * t - 0.5 * g * t**2",
        "            return axes.coords_to_point(x, y)",
        "",
        "        path = ParametricFunction(",
        "            lambda t: trajectory(t),",
        "            t_range=[0, t_flight],",
        "            color=TEAL_C,",
        "            stroke_width=4,",
        "        )",
        "",
        "        # Dots and Vectors",
        "        start_point = axes.coords_to_point(0, h0)",
        "        end_point = axes.coords_to_point(x_range_total, 0)",
        "        start_dot = Dot(start_point, color=ORANGE, radius=0.08)",
        "        end_dot = Dot(end_point, color=RED_C, radius=0.08)",
        "",
        "        # Initial velocity vector",
        "        v0_vector_end = start_point + np.array([vx, vy0, 0]) * 0.15 # Scale for visualization",
        "        initial_velocity_vector = Arrow(start_point, v0_vector_end, buff=0, color=GREEN_C, stroke_width=4, tip_length=0.2)",
        "        v0_label = MathTex(r'\\vec{v}_0', color=GREEN_C, font_size=20).next_to(initial_velocity_vector, UR, buff=0.1)",
        "",
        "        # Dashed lines for h0 and x_range_total",
        "        h0_line = DashedLine(axes.coords_to_point(0, h0), axes.coords_to_point(0, 0), color=GRAY_A, stroke_width=1.5)",
        "        h0_label_text = MathTex(f'h_0 = {h0:.0f}\\,\\mathrm{{m}}', color=GRAY_A, font_size=18).next_to(axes.coords_to_point(0, h0/2), LEFT, buff=0.2)",
        "",
        "        x_range_line = DashedLine(axes.coords_to_point(x_range_total, 0), axes.coords_to_point(0, 0), color=GRAY_A, stroke_width=1.5)",
        "        x_range_label_text = MathTex(f'S_x = {x_range_total_rounded:.0f}\\,\\mathrm{{m}}', color=GRAY_A, font_size=18).next_to(axes.coords_to_point(x_range_total/2, 0), DOWN, buff=0.2)",
        "",
        "        # Group all axes related objects",
        "        axes_group = VGroup(axes, x_label, y_label, path, start_dot, end_dot, initial_velocity_vector, v0_label, h0_line, h0_label_text, x_range_line, x_range_label_text)",
        "        axes_group.scale_to_fit_width(frame_width * 0.88)",
        "        axes_group.scale_to_fit_height(middle_zone_height * 0.82)",
        "        # Ensure it's not too small (BUG #4-ก)",
        "        if axes_group.width < frame_width * 0.55:",
        "            axes_group.scale_to_fit_width(frame_width * 0.55)",
        "        if axes_group.height < middle_zone_height * 0.55:",
        "            axes_group.scale_to_fit_height(middle_zone_height * 0.55)",
        "        axes_group.move_to(middle_center)",
        "",
        "        # --- Step 1: Calculate initial velocities (Bottom Zone) ---",
        "        step_title_1 = VGroup(",
        "            Text('ขั้นตอนที่ 1:', font='TH Sarabun New', font_size=26, color=GOLD_B),",
        "            Text('แยกองค์ประกอบความเร็วต้น', font='TH Sarabun New', font_size=26, color=GOLD_B)",
        "        ).arrange(DOWN, aligned_edge=LEFT, buff=0.08)",
        "        eq_vx = MathTex(r'v_x = v_0 \\cos\\theta = 25 \\cos(-37^\\circ) \\approx 19.97\\,\\mathrm{m/s}', font_size=26, color=BLUE_C)",
        "        eq_vy0 = MathTex(r'v_{y0} = v_0 \\sin\\theta = 25 \\sin(-37^\\circ) \\approx -15.05\\,\\mathrm{m/s}', font_size=26, color=BLUE_C)",
        "        step_group_1 = VGroup(step_title_1, eq_vx, eq_vy0).arrange(DOWN, aligned_edge=LEFT, buff=0.25)",
        "        if step_group_1.width > frame_width * 0.88:",
        "            step_group_1.scale_to_fit_width(frame_width * 0.88)",
        "        if step_group_1.height > bottom_zone_height * 0.88:",
        "            step_group_1.scale_to_fit_height(bottom_zone_height * 0.88)",
        "        step_group_1.move_to(bottom_center)",
        "",
        "        # --- Step 2: Find Time of Flight (Bottom Zone) ---",
        "        step_title_2 = VGroup(",
        "            Text('ขั้นตอนที่ 2:', font='TH Sarabun New', font_size=26, color=GOLD_B),",
        "            Text('หาเวลาที่วัตถุตกถึงพื้น (t)', font='TH Sarabun New', font_size=26, color=GOLD_B)",
        "        ).arrange(DOWN, aligned_edge=LEFT, buff=0.08)",
        "        eq_y_formula = MathTex(r's_y = v_{y0}t + \\frac{1}{2}gt^2', font_size=26, color=BLUE_C)",
        "        eq_y_sub = MathTex(f'50 = (-15.05)t + \\frac{{1}}{{2}}(10)t^2', font_size=26, color=BLUE_C)",
        "        eq_y_quad = MathTex(r'5t^2 - 15.05t - 50 = 0', font_size=26, color=BLUE_C)",
        "        eq_t_solve = MathTex(f't = {t_flight_rounded:.2f}\\,\\mathrm{{s}}', font_size=26, color=GREEN_C)",
        "        step_group_2 = VGroup(step_title_2, eq_y_formula, eq_y_sub, eq_y_quad, eq_t_solve).arrange(DOWN, aligned_edge=LEFT, buff=0.25)",
        "        if step_group_2.width > frame_width * 0.88:",
        "            step_group_2.scale_to_fit_width(frame_width * 0.88)",
        "        if step_group_2.height > bottom_zone_height * 0.88:",
        "            step_group_2.scale_to_fit_height(bottom_zone_height * 0.88)",
        "        step_group_2.move_to(bottom_center)",
        "",
        "        # --- Step 3: Find Horizontal Range (Bottom Zone) ---",
        "        step_title_3 = VGroup(",
        "            Text('ขั้นตอนที่ 3:', font='TH Sarabun New', font_size=26, color=GOLD_B),",
        "            Text('หาระยะทางที่ก้อนหินตกห่างจากตัวตึก (S_x)', font='TH Sarabun New', font_size=26, color=GOLD_B)",
        "        ).arrange(DOWN, aligned_edge=LEFT, buff=0.08)",
        "        eq_x_formula = MathTex(r's_x = v_x t', font_size=26, color=BLUE_C)",
        "        eq_x_sub = MathTex(f's_x = (19.97)({t_flight_rounded:.2f})', font_size=26, color=BLUE_C)",
        "        eq_x_solve = MathTex(f's_x = {x_range_total_rounded:.0f}\\,\\mathrm{{m}}', font_size=26, color=GREEN_C)",
        "        step_group_3 = VGroup(step_title_3, eq_x_formula, eq_x_sub, eq_x_solve).arrange(DOWN, aligned_edge=LEFT, buff=0.25)",
        "        if step_group_3.width > frame_width * 0.88:",
        "            step_group_3.scale_to_fit_width(frame_width * 0.88)",
        "        if step_group_3.height > bottom_zone_height * 0.88:",
        "            step_group_3.scale_to_fit_height(bottom_zone_height * 0.88)",
        "        step_group_3.move_to(bottom_center)",
        "",
        "        # --- Call to Action (Bottom Zone) ---",
        "        cta_text_line1 = Text('การแยกวิเคราะห์การเคลื่อนที่ในแต่ละแกน', font='TH Sarabun New', font_size=26, color=WHITE)",
        "        cta_text_line2 = Text('ช่วยให้แก้โจทย์โพรเจกไทล์ได้อย่างเป็นระบบ', font='TH Sarabun New', font_size=26, color=WHITE)",
        "        cta_text = VGroup(cta_text_line1, cta_text_line2).arrange(DOWN, aligned_edge=CENTER, buff=0.1)",
        "        if cta_text.width > frame_width * 0.88:",
        "            cta_text.scale_to_fit_width(frame_width * 0.88)",
        "        if cta_text.height > bottom_zone_height * 0.88:",
        "            cta_text.scale_to_fit_height(bottom_zone_height * 0.88)",
        "        cta_text.move_to(bottom_center)",
        "",
        "        # --- Animations ---",
        "        # Hook & Problem Display",
        "        self.play(FadeIn(problem_text, shift=UP*0.15))",
        "        self.wait(9.5)",
        "",
        "        # Diagram Explanation",
        "        self.play(",
        "            FadeOut(problem_text, shift=DOWN*0.1),",
        "            Create(axes),",
        "            Create(x_label),",
        "            Create(y_label),",
        "            Create(h0_line),",
        "            Create(h0_label_text),",
        "            GrowFromCenter(start_dot),",
        "            Create(initial_velocity_vector),",
        "            FadeIn(v0_label, shift=UP*0.15)",
        "        )",
        "        self.play(Create(path))",
        "        self.play(GrowFromCenter(end_dot))",
        "        self.wait(12.0)",
        "",
        "        # Step 1: Calculate initial velocities",
        "        self.play(FadeIn(step_group_1, shift=UP*0.15))",
        "        self.wait(15.5)",
        "",
        "        # Step 2: Find Time of Flight",
        "        self.play(",
        "            FadeOut(step_group_1, shift=DOWN*0.1),",
        "            FadeIn(step_group_2, shift=UP*0.15)",
        "        )",
        "        self.wait(13.5)",
        "",
        "        # Step 3: Find Horizontal Range",
        "        self.play(",
        "            FadeOut(step_group_2, shift=DOWN*0.1),",
        "            FadeIn(step_group_3, shift=UP*0.15),",
        "            Create(x_range_line),",
        "            FadeIn(x_range_label_text, shift=UP*0.15)",
        "        )",
        "        self.wait(9.5)",
        "",
        "        # Call to Action",
        "        self.play(",
        "            FadeOut(step_group_3, shift=DOWN*0.1),",
        "            FadeIn(cta_text, shift=UP*0.15)",
        "        )",
        "        self.wait(5.0)"
      ]
}

if __name__ == "__main__":
    engine = Manim_Engine(output_dir="renders")
    result = engine.render_episode(sample_episode)
    print(result)

    if result["status"] == "success":
        # Uncomment once firebase_client.py has a real service account key configured
        # from app.storage.video_storage import upload_manim_render
        # upload_manim_render(uid="test-uid-123", episode_number=1)
        pass